### ISSUE TITLE
Error using 3k protobuf model

### ISSUE THREAD

**Issue by lagunabravo** [kahst/BirdNET-Analyzer#57]
When trying to use the recently released 3k protobuf model I get the error `'_UserObject' object has no attribute 'predict'` and a warning that indicates that the "keras_metadata.pb" is missing. 
Should a "keras_metadata.pb" file be present with the 3k protobuf model?
Thanks!

**Comment by abfleishman** [comment]
@lagunabravo I did not get that error. Seems like maybe a path issue?

**Comment by lagunabravo** [comment]
Thank you @abfleishman for the suggestion. I'm pretty sure it is not a path issue, as the model loads. I was quite succinct in my first post, the warning it gives, hinted in my question is:
`WARNING:tensorflow:SavedModel saved prior to TF 2.5 detected when loading Keras model. Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save(). To confirm, there should be a file named "keras_metadata.pb" in the SavedModel directory.` 
A "keras_metadata.pb" is present with the 2k model, so I thought it may be just an absent file. I wonder if there is something else I'm missing, I'm using TF/Keras 2.6. You do successfully run the protobuf not the .tflite one?

**Comment by abfleishman** [comment]
@iamjeff any thoughts for lagunabravo?

**Comment by rehroman** [comment]
I am running into the same issue. 
As @lagunabravo wrote: The "keras_metadata.pb" is still present with the 2k model, and so does the following operation work without the error messages `_UserObject' object has no attribute 'predict` And also without the mentioned warning.

The error would occur already after the following lines. In this case it works, as it is the V2.1. 
`model = tf.keras.models.load_model(".../BirdNET-Analyzer/checkpoints/V2.1/BirdNET_GLOBAL_2K_V2.1_Model/")
print(model.summary())`

As the warning says,maybe it was either not saved correctly: `Please ensure that you are saving the model with model.save() or tf.keras.models.save_model(), *NOT* tf.saved_model.save().`
Or it was saved with a TF version prior to 2.5?
`WARNING:tensorflow:SavedModel saved prior to TF 2.5 detected when loading Keras model.`

Help is much appriciated.

**Comment by Josef-Haupt** [comment]
This issue concerns an outdated model.
Please reopen if encountered again.

**Comment by sulzbals** [comment]
The problem persists with the most recent checkpoint (V2.4). I tested all checkpoints starting from V2.0 and the protobuf model does not seem to work since V2.2.

I tried running the `analyze.py` script (latest code - 87628840c387e5267b1fac67b9dbb6d0393b5a64) with default parameters on the example input file. I only changed the `config.py` file in order to select the protobuf model and to adjust the model paths for testing each checkpoint ranging from V2.0 to V2.4. It worked perfectly with checkpoints V2.0 and V2.1, but when using any of the checkpoints starting from V2.2 onward I always got this same problem.

The full error message I got:

```
Traceback (most recent call last):
  File "/home/sulzbals/git/BirdNET-Analyzer/analyze.py", line 287, in analyzeFile
    p = predict(samples)
  File "/home/sulzbals/git/BirdNET-Analyzer/analyze.py", line 225, in predict
    prediction = model.predict(data)
  File "/home/sulzbals/git/BirdNET-Analyzer/model.py", line 330, in predict
    prediction = PBMODEL.predict(sample)
AttributeError: '_UserObject' object has no attribute 'predict'
```

**Comment by Josef-Haupt** [comment]
I tested this with the current repo and tensorflow 2.15.0.
The PB model is working for me.
